### ISSUE TITLE
(edited) fails on /dev/stdin

### ISSUE THREAD

**Issue by benchonaut** [slunak/rbl-checker#6]
.. see below comment

**Comment by slunak** [comment]
I can't reproduce it. It works well for me. It looks like your RBL file is corrupt. Looking at command line you provided it seems to me that order of command arguments is wrong.

**Comment by benchonaut** [comment]
( sorry , copied wrong command ..

 echo "1.1.1.1" | perl rbl-checker.pl /dev/stdin blacklist.txt display  ..
 
 and it fails silenty , seems the filehandle is read more than once:

 ( 
 
INSTANT_QUIT:  cat mta-list.txt | perl rbl-checker.pl /dev/stdin blacklist.txt  display 
          NO_QUIT:  perl rbl-checker.pl mta-list.txt blacklist.txt  display

**Comment by slunak** [comment]
Hey, I did not make it to work with /dev/stdin. This code was written ages ago and back then I did not even know what it was. The script supports only filenames as command arguments. It would be handy to support virtual files as well. You are free to add this support and share your work via a PR.
